version: '3'

services:
  app:
    image: node:24.13.0-alpine3.22
    command: sh -c "yarn install && PORT=5003 yarn dev"
    volumes:
      - ./components:/app/components
      - ./db:/app/db
      - ./next-env.d.ts:/app/next-env.d.ts
      - ./package.json:/app/package.json
      - ./pages:/app/pages
      - ./tsconfig.json:/app/tsconfig.json
      - ./types:/app/types
      - ./utils:/app/utils
      - ./yarn.lock:/app/yarn.lock
      - cache:/usr/local/share/.cache/yarn/v6
      - /app/node_modules
      - .:/app
    ports:
      - 5003:5003
    env_file:
      - .env
    working_dir: /app
    restart: always

volumes:
  dbdata:
  node_modules:
  cache:

networks:
  proxy_net:
    driver: bridge