version: '3'

services:
  development:
    image: node:24.13.0-alpine3.22
    command: sh -c "yarn install && yarn migrations && PORT=3000 yarn dev"
    volumes:
      - ./components:/app/components
      - ./db:/app/db
      - ./next-env.d.ts:/app/next-env.d.ts
      - ./package.json:/app/package.json
      - ./pages:/app/pages
      - ./tsconfig.json:/app/tsconfig.json
      - ./types:/app/types
      - ./utils:/app/utils
      - ./yarn.lock:/app/yarn.lock
      - cache:/usr/local/share/.cache/yarn/v6
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    working_dir: /app
    restart: unless-stopped
    networks:
      - proxy_net

  test_cloud:
    image: node:24.13.0-alpine3.22
    command: sh -c "yarn install && npm run migrations && npm run test"
    ports: 
      - 5005:5004
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./test:/app/test
      - ./jest.config.js:/app/jest.config.js
      - ./db:/app/db
      - ./package.json:/app/package.json
      - ./pages:/app/pages
      - ./tsconfig.json:/app/tsconfig.json
      - ./utils:/app/utils
      - cache:/usr/local/share/.cache/yarn/v6
      - node_modules:/app/node_modules
    networks:
      - proxy_net

  app:
    image: node:24.13.0-alpine3.22
    command: sh -c "yarn install && yarn migrations && PORT=5003 yarn dev"
    volumes:
      - ./components:/app/components
      - ./db:/app/db
      - ./next-env.d.ts:/app/next-env.d.ts
      - ./package.json:/app/package.json
      - ./pages:/app/pages
      - ./tsconfig.json:/app/tsconfig.json
      - ./types:/app/types
      - ./utils:/app/utils
      - ./yarn.lock:/app/yarn.lock
      - cache:/usr/local/share/.cache/yarn/v6
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/postgres
      - ENV=local
    env_file:
      - .env
    working_dir: /app
    restart: always

  test:
    image: node:24.13.0-alpine3.22
    command: sh -c "yarn install && npm run migrations && npm run test"
    ports: 
      - 3001:3001
    environment:
      DB_URL: postgres://postgres:postgres@db_test:5432/postgres
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./test:/app/test
      - ./jest.config.js:/app/jest.config.js
      - ./db:/app/db
      - ./package.json:/app/package.json
      - ./pages:/app/pages
      - ./tsconfig.json:/app/tsconfig.json
      - ./utils:/app/utils
      - cache:/usr/local/share/.cache/yarn/v6
      - node_modules:/app/node_modules
    depends_on:
      - db_test

  db:
    image: postgres:17.7
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5440
    ports:
      - 5440:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always

  db_test:
    image: postgres:17.7
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5441
    ports:
      - 5441:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always

  proxy_reverse:
    image: nginx:alpine
    restart: unless-stopped
    container_name: proxy_reverse
    ports:
      - "80:80"
    depends_on:
      - development
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy_net

volumes:
  dbdata:
  node_modules:
  cache:

networks:
  proxy_net:
    driver: bridge