worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # El DNS interno de Docker. Si development no responde rápido, Nginx no crashea el CPU
    resolver 127.0.0.11 valid=30s;

    upstream dev {
        # max_fails y fail_timeout calman a Nginx si la app se está inicializando
        server development:3000 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://dev;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Timeouts para que Nginx no se quede esperando eternamente
            proxy_connect_timeout       5s;
            proxy_send_timeout          10s;
            proxy_read_timeout          10s;
        }
    }
}