import Layout from "../components/Layout";
import '../utils/global.css';
import '../utils/normalize.css';
import { MyContextProvider } from '../utils/MyContext';
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import Head from 'next/head';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }) {
  return (
    <MyContextProvider>
      <Head>
        <title>Base Builder</title>
        <link rel="icon" href="https://cdn.icon-icons.com/icons2/1859/PNG/512/checklist_117966.png" sizes="any" />
      </Head>
      <Component className={`${geistSans.variable} ${geistMono.variable} antialiased`} {...pageProps} />
      <ToastContainer 
          position="top-right"
          autoClose={4000}       // Tiempo en milisegundos para cerrarse solo
          hideProgressBar={false} // Muestra u oculta la barra de progreso inferior
          newestOnTop={false}
          closeOnClick            // Se cierra al hacerle click encima
          rtl={false}
          pauseOnFocusLoss
          draggable               // Permite arrastrar el toast para quitarlo
          //pauseOnHover            // Pausa el tiempo si el mouse está encima
          theme="colored"         // Opciones: "light", "dark", "colored" (¡Prueba 'colored' para fondos con color sólido!)
        />
    </MyContextProvider>
  );
}
export default MyApp;

